public enum SubmenuOpcoes {

    CADASTRAR_SEGUROPF, CADASTRAR_SEGUROPJ, CADASTRAR_FROTA, CADASTRAR_CONDUTOR, CADASTRAR_CLIENTEPF, Listar_Sinistro_por_Cliente, Listar_Veiculo_por_Cliente, CADASTRAR_CLIENTEPJ,CADASTRAR_VEICULO, CADASTRAR_SEGURADORA, VOLTAR,LISTAR_CLIENTES, LISTAR_SINISTROS, LISTAR_VEICULOS, EXCLUIR_CLIENTE, EXCLUIR_VEICULO, EXCLUIR_SINISTRO,

}
